CREATE TABLE thumbnail (
    id          INT NOT NULL AUTO_INCREMENT,
    created_on  DATETIME NOT NULL,
    modified_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    url         VARCHAR(1024) NOT NULL,
    digest      VARCHAR(32) DEFAULT NULL,
    is_finished TINYINT(1) UNSIGNED DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE unique_url (url(254))
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
