CREATE TABLE update_title10 (
    created_on  TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
    url         VARCHAR(1024) NOT NULL,
    title       VARCHAR(512) DEFAULT NULL,
    status      SMALLINT(3) UNSIGNED DEFAULT 0
) ENGINE=QUEUE DEFAULT CHARSET=utf8;
